### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by skajer** [gmasse/esp-modbus-mqtt#10]
Hi, I have problem with this part of compilation.

Platform used to compile: WSL Ubuntu

Compiling .pio/build/fm-devkit/lib1f6/WiFiClientSecure/WiFiClientSecure.cpp.o
.pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp: In member function 'void WiFiManager::WiFiEvent(arduino_event_id_t, system_event_info_t)':
Compiling .pio/build/fm-devkit/lib1f6/WiFiClientSecure/esp_crt_bundle.c.o
.pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp:2877:17: warning: comparison between 'enum arduino_event_id_t' and 'enum system_event_id_t' [-Wenum-compare]
     if(event == SYSTEM_EVENT_STA_DISCONNECTED){
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp:2888:20: warning: comparison between 'enum arduino_event_id_t' and 'enum system_event_id_t' [-Wenum-compare]
   else if(event == SYSTEM_EVENT_SCAN_DONE){
                    ^~~~~~~~~~~~~~~~~~~~~~
.pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp: In member function 'void WiFiManager::WiFi_autoReconnect()':
.pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp:2903:65: error: no matching function for call to 'WiFiClass::onEvent(std::_Bind_helper<false, void (WiFiManager::*)(arduino_event_id_t, system_event_info_t), WiFiManager*, const std::_Placeholder<1>&, const std::_Placeholder<2>&>::type)'
       WiFi.onEvent(std::bind(&WiFiManager::WiFiEvent,this,_1,_2));
                                                                 ^
In file included from /home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiSTA.h:28,
                 from /home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFi.h:32,
                 from .pio/libdeps/fm-devkit/WifiManager/WiFiManager.h:59,
                 from .pio/libdeps/fm-devkit/WifiManager/WiFiManager.cpp:13:
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:161:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventCb, arduino_event_id_t)'
     wifi_event_id_t onEvent(WiFiEventCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:161:21: note:   no known conversion for argument 1 from 'std::_Bind_helper<false, void (WiFiManager::*)(arduino_event_id_t, system_event_info_t), WiFiManager*, const std::_Placeholder<1>&, const std::_Placeholder<2>&>::type' {aka 'std::_Bind<void (WiFiManager::*(WiFiManager*, std::_Placeholder<1>, std::_Placeholder<2>))(arduino_event_id_t, system_event_info_t)>'} to 'WiFiEventCb' {aka 'void (*)(arduino_event_id_t)'}
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:162:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventFuncCb, arduino_event_id_t)'
     wifi_event_id_t onEvent(WiFiEventFuncCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:162:21: note:   no known conversion for argument 1 from 'std::_Bind_helper<false, void (WiFiManager::*)(arduino_event_id_t, system_event_info_t), WiFiManager*, const std::_Placeholder<1>&, const std::_Placeholder<2>&>::type' {aka 'std::_Bind<void (WiFiManager::*(WiFiManager*, std::_Placeholder<1>, std::_Placeholder<2>))(arduino_event_id_t, system_event_info_t)>'} to 'WiFiEventFuncCb' {aka 'std::function<void(arduino_event_id_t, arduino_event_info_t)>'}
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:163:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventSysCb, arduino_event_id_t)'
     wifi_event_id_t onEvent(WiFiEventSysCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
/home/skajer/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:163:21: note:   no known conversion for argument 1 from 'std::_Bind_helper<false, void (WiFiManager::*)(arduino_event_id_t, system_event_info_t), WiFiManager*, const std::_Placeholder<1>&, const std::_Placeholder<2>&>::type' {aka 'std::_Bind<void (WiFiManager::*(WiFiManager*, std::_Placeholder<1>, std::_Placeholder<2>))(arduino_event_id_t, system_event_info_t)>'} to 'WiFiEventSysCb' {aka 'void (*)(arduino_event_t*)'}
Archiving .pio/build/fm-devkit/libe82/libWebServer.a
*** [.pio/build/fm-devkit/lib0f5/WifiManager/WiFiManager.cpp.o] Error 1

**Comment by gmasse** [comment]
Hi @skajer,

In `lib_deps_external` section of your `platformio.ini` file, can you replace the following line:
>`   https://github.com/tzapu/WiFiManager.git#4a98ba0e29606c684e66fa80e53f1293a269540b`

by
>`  https://github.com/tzapu/WiFiManager.git`

I have not tested the behaviour but the code would compile now.
Germain

**Comment by gmasse** [comment]
Fixed in #11
