### ISSUE TITLE
2-way gateway: monitor MQTT topics to write MODBUS registers

### ISSUE THREAD

**Issue by dewi-ny-je** [gmasse/esp-modbus-mqtt#6]
Thanks for your work, this is a good project.
I am planning to use it to publish via MQTT values from my air heat recovery unit.

The unit however supports writing (besides various configuration settings), also a value in a specific register to set the fan speed to a certain value, or to another register to simulate pressing a physical button.

See https://www.duco.eu/Wes/CDN/1/Attachments/L8000003-informatieblad-ModBus-(nl)_637576438031698074.pdf page 7, registers 10 (set fan speed %) and 19 (set manual levels 1, 2, 3, auto or absence as if the wall unit was operated).

Could you introduce the monitor of MQTT values? if different from "null", write back to respective Modbus register, then reset to null after successful write.

**Comment by gmasse** [comment]
Hi @dewi-ny-je

Thanks for your interest in this project. Although the primary goal of this project is to poll (read-only) a Modbus slave device, you are more than welcome to contribute to match your own objectives.

Best regards,
Germain
