### ISSUE TITLE
board with rs485/can included

### ISSUE THREAD

**Issue by xjustbmw** [gmasse/esp-modbus-mqtt#8]
I got this board TTGO T-CAN485 for this exact purpose. 
Monitor some slave devices through rs485 or canbus over external mqtt.

The board It has esp32 on it and also modbus/canbus enabled available ports.
Do you think this board will work with your application ?

It would be nice to have something ready to go without any additional wiring.
PS. For places where wifi is not really available. Is there any similar device for cabled rj45 ?

regards,
Adrian

**Comment by gmasse** [comment]
Hi @xjustbmw,

It should work in theory. The source code provided by LyliGO rely on the same Modbus library.
Let's try with the following parameters in your `platformio.ini` file:
```
modbus_rxd: 21
modbus_txd: 22
modbus_rts: NOT_A_PIN
```
Please keep me informed if you succeed. In this case I will mention the hardware is compatible.

Unfortunately, I am not aware of ESP32 with RJ45 and RS485.

Regards,
Germain

**Comment by xjustbmw** [comment]
Hi Germain,

I will surely test right away and get back to you.

Only option I found so far regarding wired ethernet is WT32-ETH01 module. Aparently this has rs485 ports on it or needs pairing with a MAX485 ? Can you also take a look ?


Is there any planned option to also write registers based on a mqtt subscription ?
IE: Reset alarms, change setpoint,etc


Regards,
Adrian

**Comment by gmasse** [comment]
WT32-ETH01 does not provide RS-485 interface. You need a UART to RS-485 converter. 

Modbus write mode would definitively be a great improvement for this project. Unfortunately, I do not have any modbus device anymore. I would be pleased to help anyone who tries to implement it. 

Regards,
Germain
